# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=true
separator_block_width=15

[cpu_usage2]
command=i3blocks-contrib/cpu_usage2/cpu_usage2
markup=pango
interval=persist
min_width=CPU 100.00%
REFRESH_TIME=1
LABEL=CPU
WARN_PERCENT=50
CRIT_PERCENT=80
DECIMALS=2

[memory2]
command=i3blocks-contrib/memory2/memory2
label= 
interval=persist
markup=pango
bar_chars=_▏▎▍▌▋▊▉██
bar_size=20
critical=50
warning=20
color_critical=#d9534f

[bandwidth]
command=i3blocks-contrib/bandwidth2/bandwidth2 
interval=persist
markup=pango
LABEL=
WARN_RX=268435456
WARN_TX=268435456
CRIT_RX=536870912
CRIT_TX=536870912

[temperature]
command=i3blocks-contrib/temperature/temperature 
interval=10
T_WARN=70
T_CRIT=90

[time]
command=date '+%H:%M:%S'
interval=1
